name: Build binary files to selected branch (DANGER AREA)
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Refresh data folder from source
        run: |
          rm -rf compiled/data
          cp -rf src/data/ compiled/

  build:
    needs: prepare
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
        
    steps:
      - uses: actions/checkout@v4
        name: Checkout
          
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: ${{ matrix['python-version'] }}

      - name: Build Executables (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python3 -m ensurepip
          python -m pip install --upgrade pip
          pip install pyinstaller -r src/requirements.txt
          pyinstaller .github/CIBuildFIles/buildWindows.spec

      - name: Upload Artifacts (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: pyRogue-Windows
          path: |
            dist/pyRogue-windows.exe

      - name: Build Executables (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          pip install pyinstaller -r src/requirements.txt
          pyinstaller .github/CIBuildFIles/buildLinux.spec

      - name: Upload Artifacts (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: pyRogue-Linux
          path: |
            dist/pyRogue-Linux.sh
      
      - name: Build Executables (Mac)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          pip install pyinstaller -r src/requirements.txt
          pyinstaller .github/CIBuildFIles/buildMac.spec

      - name: Upload Artifacts (Mac)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: pyRogue-MacIntel
          path: |
            dist/pyRogue-MacIntel.sh
